collectorApp/collector/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "collector"

urlpatterns=[
    path("login/", auth_views.LoginView.as_view(template_name="collector/login.html"),
    name = "login"),
    path("logout/", auth_views.LogoutView.as_view(), name ="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),


]

collectorApp/collectorApp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path("", views.HomePage.as_view(), name ="home"),
    path("admin/", admin.site.urls),
    path("collector/", include("collector.urls",namespace = "collector")),
    path("collector/", include("django.contrib.auth.urls")),
    path("test/", views.TestPage.as_view(), name="test"),
    path("thanks/", views.ThanksPage.as_view(), name="thanks"),
    re_path(r'^posts/',include("posts.urls",namespace="posts")),
    re_path(r'^groups/',include("groups.urls",namespace="groups")),
    

]

collectorApp/posts/urls.py
#urls.py
from django.urls import include, re_path

from . import views

app_name = "posts"

urlpatterns = [
re_path(r'^$',views.PostList.as_view(),name="all"),
re_path(r'new/$',views.CreatePost.as_view(),name="create"),
re_path(r'by/(?P<username>[-\w]+)', views.UserPosts.as_view(),name="for_user"),
re_path(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetail.as_view(),name="single"),
re_path(r'delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name="delete"),

]

collectorApp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Collector App</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'collector/css/master.css'%}">



  </head>
  <body>
    <nav class="navbar mynav" role="navigation" id="navbar">
        <div class="container">
            <a class="navbar-brand mynav" href="{%url 'home' %}"><img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSg6Su-byWkX7UBRFMs_y6k3um6TGV8XpKe_ZJxnvFerOj7YmlV" class="image-fluid" style="max-width: 20px; max-height: 24px" alt="Collector"></a>
            <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
                <li><a href="{% url "posts:create"  %}">Post</a></li>
                <li><a href="{% url "groups:all"  %}">Groups</a></li>
                <li><a href="{% url "groups:create"  %}">Create Group</a></li>
                <li><a href="{% url 'collector:logout' %}">Log Out</a></li>
              {% else %}
                <li><a href="{% url "groups:all"  %}">Groups</a></li>
                <li><a href="{% url 'collector:login' %}">Log In</a></li>
                <li><a href="{% url 'collector:signup' %}">Sign Up</a></li>
              {% endif %}
            </ul>

        </div>
    </nav>

<div class="container mycontent">

    {% block content %}

    {% endblock %}
</div>

  <canvas id="canvas"></canvas>

</body>
  <script src="{% static "collector/js/master.js"%}" type="text/javascript" ></script>
</html>

collectorApp/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="box">
    <div class="title-box">
      <img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSg6Su-byWkX7UBRFMs_y6k3um6TGV8XpKe_ZJxnvFerOj7YmlV" alt="Collector">
      <h1>Welcome to Collector App!</h1>
    </div>


{% endblock %}

collectorApp/templates/test.html
{% extends "base.html" %}
{% block content %}

<h1>You are now logged in!</h1>

{% endblock %}

collectorApp/templates/thanks.html
{% extends "base.html" %}
{% block content %}

<h1>Thanks for visiting, come back soon!</h1>

{% endblock %}